Add Global bash lint (Shellcheck)

diff --git a/functions/wazzuf-check b/functions/wazzuf-check
--- a/functions/wazzuf-check
+++ b/functions/wazzuf-check
@@ -1,229 +1,231 @@
+#!/bin/bash
 ## check functions
 
 checkandsource_wazzuf_conf () {
-	if [ ! -f ${CONF_FILE} ]; then
-		echo -ne "\n *************************************\n"
-		echo -ne " ${CONF_FILE} configuration file not found !\n"
-		echo -ne " Copying an example: please fill some informations in it !\n"
-		mkdir -p ${CONF_PATH_BASE}
-		cp -v ${CONF_FILE_EXAMPLE} ${CONF_FILE}
-		echo -ne " Exiting...\n"
-		echo -ne " *************************************\n"
-		exit 1
-	else
-		if [[ ${DEBUG} == "1" ]]; then echo "DEBUG Sourcing ${CONF_FILE}..."; fi
-		source ${CONF_FILE}
-	fi
+  if [ ! -f "${CONF_FILE}" ]; then
+    echo -ne "\n *************************************\n"
+    echo -ne " ${CONF_FILE} configuration file not found !\n"
+    echo -ne " Copying an example: please fill some informations in it !\n"
+    mkdir -p "${CONF_PATH_BASE}"
+    cp -v "${CONF_FILE_EXAMPLE}" "${CONF_FILE}"
+    echo -ne " Exiting...\n"
+    echo -ne " *************************************\n"
+    exit 1
+  else
+    if [[ "${DEBUG}" == 1 ]]; then echo "DEBUG Sourcing ${CONF_FILE}..."; fi
+    # shellcheck source=conf/wazzuf-ripper.conf
+    source "${CONF_FILE}"
+  fi
 }
 
 checkandsource_wazzuf_files () {
-	for WFILE in ${WAZZUF_FILES}
-	do
-		if [ ! -f ${WFILE} ]; then
-			echo -ne "\n *************************************\n"
-			echo -ne " ${WFILE} file not found ! Exiting...\n"
-			echo -ne " *************************************\n"
-		        exit 1
-		else	
-			if [[ ${DEBUG} == "1" ]]; then echo "DEBUG Sourcing ${WFILE}..."; fi
-			source ${WFILE}
-		fi
-	done
+  for WFILE in ${WAZZUF_FILES}; do
+    if [ ! -f "${WFILE}" ]; then
+      echo -ne "\n *************************************\n"
+      echo -ne " ${WFILE} file not found ! Exiting...\n"
+      echo -ne " *************************************\n"
+      exit 1
+    else
+      if [[ "${DEBUG}" == "1" ]]; then echo "DEBUG Sourcing ${WFILE}..."; fi
+      # shellcheck source=/dev/null
+      source "${WFILE}"
+    fi
+  done
 }
 
 # Check if user is not a super-user (root)
 check_user () {
-if [[ ${EUID} -eq 0 ]]; then
-	echo " ########################"
-	echo " # Do not run as root ! #"
-	echo " ########################"
-	exit 1
+if [[ "${EUID}" -eq 0 ]]; then
+  echo " ########################"
+  echo " # Do not run as root ! #"
+  echo " ########################"
+  exit 1
 fi
 } 
 
 # check if value is an integer
 # need  NUMBER_TO_CHECK
-#	MESSAGE
-#	WAZZUF_UI
+# MESSAGE
+# WAZZUF_UI
 #
 # return nothing
 check_integer () {
-	if echo ${NUMBER_TO_CHECK} | egrep -vq '^[0-9]+$'; then
-		if [[ ${WAZZUF_UI} == "GUI" ]]; then
-			zenity --error --title "${ZEN_TITLE}" \
-				--text "${MESSAGE} is not an integer ! Exiting."
-		else
-			echo -ne " Error ! ${MESSAGE} is not an integer ! Exiting.\n"
-		fi
-		exit 1
-	fi
+  if echo "${NUMBER_TO_CHECK}" | grep -vEq '^[0-9]+$'; then
+    if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+      zenity --error --title "${ZEN_TITLE}" \
+        --text "${MESSAGE} is not an integer ! Exiting."
+    else
+      echo -ne " Error ! ${MESSAGE} is not an integer ! Exiting.\n"
+    fi
+    exit 1
+  fi
 }
 
 # check if missing softwares
 check_omdb () {
-	if [ ! -x /usr/bin/omdbtool ]; then
-		SOFT_NAME="omdb-cli"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/omdbtool ]; then
+    SOFT_NAME="omdb-cli"
+    soft_to_install_exit
+  fi
 }
 
 check_nice () {
-	if [ ! -x "/usr/bin/nice" ]; then
-		SOFT_NAME="nice (coreutils)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/nice ]; then
+    SOFT_NAME="nice (coreutils)"
+    soft_to_install_exit
+  fi
 }
 
 check_ionice () {
-	if [ ! -x "/usr/bin/ionice" ]; then
-		SOFT_NAME="ionice (util-linux)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/ionice ]; then
+    SOFT_NAME="ionice (util-linux)"
+    soft_to_install_exit
+  fi
 }
 
 check_ogmtools () {
-	if [ ! -x "/usr/bin/dvdxchap" ]; then
-		SOFT_NAME="dvdxchap (ogmtools)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/dvdxchap ]; then
+    SOFT_NAME="dvdxchap (ogmtools)"
+    soft_to_install_exit
+  fi
 }
 
 check_bdchapters () {
-	if [ ! -x "/usr/bin/bdchapters" ]; then
-		SOFT_NAME="bdchapters"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/bdchapters ]; then
+    SOFT_NAME="bdchapters"
+    soft_to_install_exit
+  fi
 }
 
 check_lsdvd () {
-	if [ ! -x "/usr/bin/lsdvd" ]; then
-		SOFT_NAME="lsdvd"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/lsdvd ]; then
+    SOFT_NAME="lsdvd"
+    soft_to_install_exit
+  fi
 }
 
 check_mediainfo () {
-	if [ ! -x "/usr/bin/mediainfo" ]; then
-		SOFT_NAME="mediainfo"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/mediainfo ]; then
+    SOFT_NAME="mediainfo"
+    soft_to_install_exit
+  fi
 }
 
 check_avconv () {
-	if [ ! -x "/usr/bin/avconv" ]; then
-		SOFT_NAME="avconv (libav-tools)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/avconv ]; then
+    SOFT_NAME="avconv (libav-tools)"
+    soft_to_install_exit
+  fi
 }
 
 check_ffmpeg () {
-	if [ ! -x "/usr/bin/ffmpeg" ]; then
-		SOFT_NAME="ffmpeg"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/ffmpeg ]; then
+    SOFT_NAME="ffmpeg"
+    soft_to_install_exit
+  fi
 }
 
 check_7z () {
-	if [ ! -x "/usr/bin/7z" ]; then
-		SOFT_NAME="7z (p7zip-full)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/7z ]; then
+    SOFT_NAME="7z (p7zip-full)"
+    soft_to_install_exit
+  fi
 }
 
 check_genisoimage () {
-	if [ ! -x "/usr/bin/genisoimage" ]; then
-		SOFT_NAME="genisoimage"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/genisoimage ]; then
+    SOFT_NAME="genisoimage"
+    soft_to_install_exit
+  fi
 }
 
 check_mplayer () {
-	if [ ! -x "/usr/bin/mplayer" ]; then
-		SOFT_NAME="mplayer"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/mplayer ]; then
+    SOFT_NAME="mplayer"
+    soft_to_install_exit
+  fi
 }
 
 check_mencoder () {
-	if [ ! -x "/usr/bin/mencoder" ]; then
-		SOFT_NAME="mencoder"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/mencoder ]; then
+    SOFT_NAME="mencoder"
+    soft_to_install_exit
+  fi
 }
 
 check_cvlc () {
-	if [ ! -x "/usr/bin/cvlc" ]; then
-		SOFT_NAME="cvlc (vlc)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/cvlc ]; then
+    SOFT_NAME="cvlc (vlc)"
+    soft_to_install_exit
+  fi
 }
 
 check_oggenc () {
-	if [ ! -x "/usr/bin/oggenc" ]; then
-		SOFT_NAME="oggenc (vorbis-tools)"
-		soft_to_install_exit
-	fi	
+  if [ ! -x /usr/bin/oggenc ]; then
+    SOFT_NAME="oggenc (vorbis-tools)"
+    soft_to_install_exit
+  fi  
 }
 
 check_lame () {
-	if [ ! -x "/usr/bin/lame" ]; then
-		SOFT_NAME="lame"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/lame ]; then
+    SOFT_NAME="lame"
+    soft_to_install_exit
+  fi
 }
 
 check_opusenc () {
-        if [ ! -x "/usr/bin/opusenc" ]; then
-		SOFT_NAME="opusenc (opus-tools)"
-		soft_to_install_exit
-        fi
+    if [ ! -x /usr/bin/opusenc ]; then
+      SOFT_NAME="opusenc (opus-tools)"
+      soft_to_install_exit
+    fi
 }
 
 check_imagemagick () {
-	if [ ! -x "/usr/bin/convert" ]; then
-		SOFT_NAME="convert (imagemagick)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/convert ]; then
+    SOFT_NAME="convert (imagemagick)"
+    soft_to_install_exit
+  fi
 }
 
 check_mkvmerge () {
-	if [ ! -x "/usr/bin/mkvmerge" ]; then
-		SOFT_NAME="mkvmerge (mkvtoolnix)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/mkvmerge ]; then
+    SOFT_NAME="mkvmerge (mkvtoolnix)"
+    soft_to_install_exit
+  fi
 }
 
 check_tsmuxer () {
-	if [ ! -x "/usr/bin/tsmuxer" ]; then
-		SOFT_NAME="tsmuxer (CLI)"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/tsmuxer ]; then
+    SOFT_NAME="tsmuxer (CLI)"
+    soft_to_install_exit
+  fi
 }
 
 check_ccextractor () {
-	if [ ! -x "/usr/bin/ccextractor" ]; then
-		SOFT_NAME="ccextractor"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/ccextractor ]; then
+    SOFT_NAME="ccextractor"
+    soft_to_install_exit
+  fi
 }
 
 check_wget () {
-	if [ ! -x "/usr/bin/wget" ]; then
-		SOFT_NAME="wget"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/wget ]; then
+    SOFT_NAME="wget"
+    soft_to_install_exit
+  fi
 }
 
 check_md5sum () {
-	if [ ! -x "/usr/bin/md5sum" ]; then
-		SOFT_NAME="md5sum"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/md5sum ]; then
+    SOFT_NAME="md5sum"
+    soft_to_install_exit
+  fi
 }
 
 check_udisksctl () {
-	if [ ! -x "/usr/bin/udisksctl" ]; then
-		SOFT_NAME="udisksctl"
-		soft_to_install_exit
-	fi
+  if [ ! -x /usr/bin/udisksctl ]; then
+    SOFT_NAME="udisksctl"
+    soft_to_install_exit
+  fi
 }
diff --git a/functions/wazzuf-common b/functions/wazzuf-common
--- a/functions/wazzuf-common
+++ b/functions/wazzuf-common
@@ -1,9 +1,10 @@
+#!/bin/bash
 ## common functions
 
 # Wazzuf Ripper script usage
 wazzuf_usage () {
-	echo -ne "\n Usage : $0 [ Video Codec ] [ Audio 1 Codec ] [ Audio 2 Codec ] [GUI]\n"
-	exit 1
+  echo -ne "\n Usage : $0 [ Video Codec ] [ Audio 1 Codec ] [ Audio 2 Codec ] [GUI]\n"
+  exit 1
 }
 
 # Iso file management
@@ -13,59 +14,59 @@ wazzuf_usage () {
 # first argument: "mount" or "umount"
 # second argument: "GUI" or empty
 iso_manage () {
-	case ${1} in
-	mount )
-		# Check if iso file already mounted
-		if [[ $(mount | grep udf | grep "${ISO_FILE_PATH}" | wc -l) == "1" ]]; then
-			echo "${ISO_FILE_PATH} already mounted"
-			# Get mount point
-			ISO_MOUNT_POINT=$(mount | grep udf | grep "${ISO_FILE_PATH}" | sed 's/ type udf //g'  | cut -d '(' -f 1 | awk '{print $NF}')
-		else
-			# mount iso file
-			# udisksctl does not require root privileges
-			check_udisksctl
-			if [[ ${2} == "GUI" ]]; then
-				if [[ ${DEBUG} == "1" ]]; then echo "DEBUG udisksctl loop-setup -r -f \"${ISO_FILE_PATH}\"";fi
-				udisksctl loop-setup -r -f "${ISO_FILE_PATH}"
-			else
-				echo "Mount iso file"
-				if [[ ${DEBUG} == "1" ]]; then echo "DEBUG udisksctl loop-setup -r -f \"${ISO_FILE_PATH}\"";fi
-				udisksctl loop-setup -r -f "${ISO_FILE_PATH}"
-			fi
-			# Get mount point
-			ISO_MOUNT_POINT=$(mount | grep udf | sed 's/ type udf //g'  | cut -d '(' -f 1 | awk '{print $NF}')
-		fi
-		;;
-	umount )
-		# No specific privilege required (if mounted with udisksctl)
-		if [[ ${2} == "GUI" ]]; then
-			umount "${ISO_FILE_PATH}"
-		else
-			echo "Umount iso file"
-			umount "${ISO_FILE_PATH}"
-		fi
-		;;
-	esac
+  case ${1} in
+  mount )
+    # Check if iso file already mounted
+    if [[ $(mount | grep udf | grep -c "${ISO_FILE_PATH}") == "1" ]]; then
+      echo "${ISO_FILE_PATH} already mounted"
+      # Get mount point
+      ISO_MOUNT_POINT=$(mount | grep udf | grep "${ISO_FILE_PATH}" | sed 's/ type udf //g'  | cut -d '(' -f 1 | awk '{print $NF}')
+    else
+      # mount iso file
+      # udisksctl does not require root privileges
+      check_udisksctl
+      if [[ ${2} == "GUI" ]]; then
+        if [[ "${DEBUG}" == "1" ]]; then echo "DEBUG udisksctl loop-setup -r -f \"${ISO_FILE_PATH}\"";fi
+        udisksctl loop-setup -r -f "${ISO_FILE_PATH}"
+      else
+        echo "Mount iso file"
+        if [[ "${DEBUG}" == "1" ]]; then echo "DEBUG udisksctl loop-setup -r -f \"${ISO_FILE_PATH}\"";fi
+        udisksctl loop-setup -r -f "${ISO_FILE_PATH}"
+      fi
+      # Get mount point
+      ISO_MOUNT_POINT=$(mount | grep udf | sed 's/ type udf //g'  | cut -d '(' -f 1 | awk '{print $NF}')
+    fi
+    ;;
+  umount )
+    # No specific privilege required (if mounted with udisksctl)
+    if [[ ${2} == "GUI" ]]; then
+      umount "${ISO_FILE_PATH}"
+    else
+      echo "Umount iso file"
+      umount "${ISO_FILE_PATH}"
+    fi
+    ;;
+  esac
 }
 
 # Get the type of the mounted media device
-# need  MOUNT_PATH
+# need MOUNT_PATH
 #
 # return MEDIA_DEVICE_TYPE
 get_media_device_type () {
-	check_mediainfo
-	MEDIA_FORMAT_FULL=$(mediainfo --Inform="General;%Format%" "${MOUNT_PATH}" 2> /dev/null)
-	if [[ ${DEBUG} == "1" ]]; then echo "DEBUG MEDIA_FORMAT_FULL ${MEDIA_FORMAT_FULL}";fi
+  check_mediainfo
+  MEDIA_FORMAT_FULL=$(mediainfo --Inform="General;%Format%" "${MOUNT_PATH}" 2> /dev/null)
+  if [[ "${DEBUG}" == "1" ]]; then echo "DEBUG MEDIA_FORMAT_FULL ${MEDIA_FORMAT_FULL}";fi
 
-	if [[ $(echo ${MEDIA_FORMAT_FULL} | grep Blu-ray) ]]; then
-		MEDIA_DEVICE_TYPE="BD"
-	elif [[ $(echo ${MEDIA_FORMAT_FULL} | grep DVD) ]]; then
-		MEDIA_DEVICE_TYPE="DVD"
-	else
-		# Not a DVD nor BD
-		MEDIA_DEVICE_TYPE="UNKNOWN"
-	fi
-	if [[ ${DEBUG} == "1" ]]; then echo "DEBUG MEDIA_DEVICE_TYPE ${MEDIA_DEVICE_TYPE}";fi
+  if echo "${MEDIA_FORMAT_FULL}" | grep -q Blu-ray; then
+    MEDIA_DEVICE_TYPE="BD"
+  elif echo "${MEDIA_FORMAT_FULL}" | grep -q DVD; then
+    MEDIA_DEVICE_TYPE="DVD"
+  else
+    # Not a DVD nor BD
+    MEDIA_DEVICE_TYPE="UNKNOWN"
+  fi
+  if [[ "${DEBUG}" == "1" ]]; then echo "DEBUG MEDIA_DEVICE_TYPE ${MEDIA_DEVICE_TYPE}";fi
 }
 
 # Get the name of the mounted media device
@@ -73,113 +74,113 @@ get_media_device_type () {
 #
 # return MEDIA_TITLE
 get_media_title () {
-	MEDIA_TITLE=$(echo ${MOUNT_PATH} | awk 'BEGIN {FS = "/"} ; {print $NF}')
-	if [[ ${DEBUG} == "1" ]]; then echo "DEBUG MEDIA_TITLE ${MEDIA_TITLE}";fi
+  MEDIA_TITLE=$(echo "${MOUNT_PATH}" | awk 'BEGIN {FS = "/"} ; {print $NF}')
+  if [[ "${DEBUG}" == "1" ]]; then echo "DEBUG MEDIA_TITLE ${MEDIA_TITLE}";fi
 }
 
 # soft_to_install_exit
-# need  SOFT_NAME
-#	WAZZUF_UI
+# need SOFT_NAME
+#      WAZZUF_UI
 #
 # return nothing
 soft_to_install_exit () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --error --title "${ZEN_TITLE}" \
-			--text "Please install ${SOFT_NAME} ! Exiting."
-	else
-		echo -ne "\n *************************************\n"
-		echo -ne " Please install ${SOFT_NAME} ! Exiting. \n"
-		echo -ne " *************************************\n"
-	fi
-	exit 1
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --error --title "${ZEN_TITLE}" \
+      --text "Please install ${SOFT_NAME} ! Exiting."
+  else
+    echo -ne "\n *************************************\n"
+    echo -ne " Please install ${SOFT_NAME} ! Exiting. \n"
+    echo -ne " *************************************\n"
+  fi
+  exit 1
 }
 
 # file_exists
-# need  FILE_NAME
-#	WAZZUF_UI
+# need FILE_NAME
+#      WAZZUF_UI
 #
 # return nothing
 file_exists () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --info --title "${ZEN_TITLE}" \
-			--text "${FILE_NAME} file exists. Next..." \
-			--timeout=2
-	else
-		echo -ne "\n *************************************\n"
-		echo " ${FILE_NAME} file exists. Next..."  && sleep 1
-		echo -ne " *************************************\n"
-	fi
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --info --title "${ZEN_TITLE}" \
+      --text "${FILE_NAME} file exists. Next..." \
+      --timeout=2
+  else
+    echo -ne "\n *************************************\n"
+    echo " ${FILE_NAME} file exists. Next..."  && sleep 1
+    echo -ne " *************************************\n"
+  fi
 }
 
 # dont_exists_warn
-# need  FILE_NAME
-#	SOURCE_NAME
-#	WAZZUF_UI
+# need FILE_NAME
+#      SOURCE_NAME
+#      WAZZUF_UI
 #
 # return nothing
 dont_exists_warn () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --warning --title "${ZEN_TITLE}" \
-			--text "${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Skipping..." \
-			--timeout=2
-	else
-		echo -ne "\n *************************************\n"
-		echo " Warning: ${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Skipping..." && sleep 2
-		echo -ne " *************************************\n"
-	fi
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --warning --title "${ZEN_TITLE}" \
+      --text "${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Skipping..." \
+      --timeout=2
+  else
+    echo -ne "\n *************************************\n"
+    echo " Warning: ${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Skipping..." && sleep 2
+    echo -ne " *************************************\n"
+  fi
 }
 
 # dont_exists_exit
-# need  FILE_NAME
-#	SOURCE_NAME
-#	WAZZUF_UI
+# need FILE_NAME
+#      SOURCE_NAME
+#      WAZZUF_UI
 #
 # return nothing
 dont_exists_exit () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --error --title "${ZEN_TITLE}" \
-			--text "${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Exiting..." \
-			--timeout=2
-	else
-		echo -ne "\n *************************************\n"
-		echo " Error: ${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Exiting..." && sleep 2
-		echo -ne " *************************************\n"
-	fi
-	exit 1
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --error --title "${ZEN_TITLE}" \
+      --text "${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Exiting..." \
+      --timeout=2
+  else
+    echo -ne "\n *************************************\n"
+    echo " Error: ${FILE_NAME} file does not exists in ${SOURCE_NAME} ! Exiting..." && sleep 2
+    echo -ne " *************************************\n"
+  fi
+  exit 1
 }
 
 # not_recognized_exit
-# need  MESSAGE
-#	WAZZUF_UI
+# need MESSAGE
+#      WAZZUF_UI
 #
 # return nothing
 not_recognized_exit () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --error --title "${ZEN_TITLE}" \
-			--text "${MESSAGE} not recognized ! Exiting."
-	else
-		echo -ne "\n *************************************\n"
-		echo -ne " Error: ${MESSAGE} not recognized ! Exiting. \n"
-		echo -ne " *************************************\n"
-	fi
-	exit 1
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --error --title "${ZEN_TITLE}" \
+      --text "${MESSAGE} not recognized ! Exiting."
+  else
+    echo -ne "\n *************************************\n"
+    echo -ne " Error: ${MESSAGE} not recognized ! Exiting. \n"
+    echo -ne " *************************************\n"
+  fi
+  exit 1
 }
 
 # empty_exit
-# need  MESSAGE
-#	WAZZUF_UI
+# need MESSAGE
+#      WAZZUF_UI
 #
 # return nothing
 empty_exit () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --error --title "${ZEN_TITLE}" \
-			--text "${MESSAGE} is empty ! Exiting."
-	else
-		echo -ne "\n *************************************\n"
-		echo -ne " Error: ${MESSAGE} is empty ! Exiting. \n"
-		echo -ne " *************************************\n"
-	fi
-	exit 1
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --error --title "${ZEN_TITLE}" \
+      --text "${MESSAGE} is empty ! Exiting."
+  else
+    echo -ne "\n *************************************\n"
+    echo -ne " Error: ${MESSAGE} is empty ! Exiting. \n"
+    echo -ne " *************************************\n"
+  fi
+  exit 1
 }
 
 # wazzuf_quit
@@ -187,25 +188,25 @@ empty_exit () {
 #
 # return nothing
 wazzuf_quit () {
-	zenity --info --title "${ZEN_TITLE}" \
-		--text "${ZEN_TITLE} will now quit."
-	exit 0
+  zenity --info --title "${ZEN_TITLE}" \
+    --text "${ZEN_TITLE} will now quit."
+  exit 0
 }
 
 # wazzuf_disk_full
-# need  MESSAGE
-#	WAZZUF_UI
+# need MESSAGE
+#      WAZZUF_UI
 #
 # return nothing
 disk_full_quit () {
-	if [[ ${WAZZUF_UI} == "GUI" ]]; then
-		zenity --info --title "${ZEN_TITLE}" \
-			--text "Insufficient disk space in ${MESSAGE} ! Exiting."
-	else
-		echo -ne "\n *************************************\n"
-		echo -ne " Error: Insufficient disk space in ${MESSAGE} ! Exiting. \n"
-		echo -ne " *************************************\n"
-	fi
-	exit 1
+  if [[ "${WAZZUF_UI}" == "GUI" ]]; then
+    zenity --info --title "${ZEN_TITLE}" \
+      --text "Insufficient disk space in ${MESSAGE} ! Exiting."
+  else
+    echo -ne "\n *************************************\n"
+    echo -ne " Error: Insufficient disk space in ${MESSAGE} ! Exiting. \n"
+    echo -ne " *************************************\n"
+  fi
+  exit 1
 }
 
